version: '3.6'

services:
  textractor:
    build:
      context: service
    image: textractor/app
    container_name: textractor
    ports:
      -  8060:8060
    volumes:
      - ./service:/usr/src/app
